### ISSUE TITLE
农历转公历是能否自动判断是否闰月

### ISSUE THREAD

**Issue by aveyuan** [liujiawm/gocalendar#2]
一般我们在存储日期的实话，仅仅按照日期的格式年月日来存储。然后加上一个日期类别，来判断是公历还是农历。

**Comment by aveyuan** [comment]
` c.LunarToGregorian(2020,4,14,true)` 对于农转公，能否去掉这个true，自动实现？

**Comment by aveyuan** [comment]
想错了，通过新历转农历反推就行了。

**Comment by liujiawm** [comment]
如果只是给农历的年月日，而不给出是否是闰月的话，如：农历2020年四月十四，这样的话就对应了两个公历日期，分别是2020-05-06和2020-06-05。

      在一些普通的应用中，存储用户的农历数据（主要是生日），一般是加一个是否是农历的类别判断，一些社交应用都是这样做的，这其实是不完整或者说是有局限的。准确的做法是，选择生日是农历之后，还应该显示一个选项是否是闰月。

`
（如果应用只是记录生日，其实可以忽略闰月，因为农历闰月生日如果在闰月的话，一般会改成非闰月，否则一辈子也过不了几个生日。）
`

**Comment by aveyuan** [comment]
> ```
>   如果只是给农历的年月日，而不给出是否是闰月的话，如：农历2020年四月十四，这样的话就对应了两个公历日期，分别是2020-05-06和2020-06-05。
> 
>   在一些普通的应用中，存储用户的农历数据（主要是生日），一般是加一个是否是农历的类别判断，一些社交应用都是这样做的，这其实是不完整或者说是有局限的。准确的做法是，选择生日是农历之后，还应该显示一个选项是否是闰月。
> ```
> 
> `（如果应用只是记录生日，其实可以忽略闰月，因为农历闰月生日如果在闰月的话，一般会改成非闰月，否则一辈子也过不了几个生日。）`

我非常认同您的说法，但是这个太严谨了，不太适合人们现在的情况。更多的人可能就不会/不知道自己是否闰月，所以能否开个口子，做个松散模式呢？

**Comment by liujiawm** [comment]
你在使用农历转公历时，默认用非闰月(false)就行了,如果有特另需求，我在下一个版本中会为此特别写一个方法
