### ISSUE TITLE
meet  unexpected Generate at end of statement

### ISSUE THREAD

**Issue by luckrill** [liujiawm/gocalendar#3]
my code 

import (
	"fmt"
        "github.com/liujiawm/gocalendar"
)

func main() {

(*Calendar) Generate()

	items := DefaultCalendar().Generate()
	for _, item := range items {
		fmt.Println(item)
	}

}

run meet error:
syntax error: unexpected Generate at end of statement

how to use gocalendar

**Comment by liujiawm** [comment]
```
package main

import (
	"fmt"
	"github.com/liujiawm/gocalendar"
)

func main() {
	items := gocalendar.DefaultCalendar().Generate()
	for _, item := range items {
		fmt.Println(item)
	}
}
```
